/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_struct;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeck
 */
public class Stack_frame extends javax.swing.JFrame {

    int a,b,c,d,e; 
    String Output = "";
    Integer userValue;
    ArrayList<Integer> arr = new ArrayList<>();   
    Integer i= 0;
    
    public Stack_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stack5 = new javax.swing.JTextField();
        inputValue = new javax.swing.JTextField();
        pringle = new javax.swing.JLabel();
        stack1 = new javax.swing.JTextField();
        stack2 = new javax.swing.JTextField();
        stack3 = new javax.swing.JTextField();
        stack4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output_view = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stack");
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(stack5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 44, -1));

        inputValue.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jPanel1.add(inputValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, 100, 80));

        pringle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pringle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pringle.png"))); // NOI18N
        jPanel1.add(pringle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 600));
        jPanel1.add(stack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 44, -1));

        stack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stack2ActionPerformed(evt);
            }
        });
        jPanel1.add(stack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 44, -1));
        jPanel1.add(stack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 44, -1));
        jPanel1.add(stack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 44, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("STACK SCENARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 15, -1, -1));

        home.setBackground(new java.awt.Color(255, 204, 102));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home_btn.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 15, 66, 59));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INPUT_BTN.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, -1, 90));

        btn_view.setBackground(new java.awt.Color(255, 204, 204));
        btn_view.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_view.setForeground(new java.awt.Color(255, 153, 0));
        btn_view.setText("VIEW");
        btn_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewMouseClicked(evt);
            }
        });
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TAZ.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 132, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 102, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 204));
        jButton3.setText("EAT");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 363, -1, -1));

        output_view.setColumns(20);
        output_view.setRows(5);
        jScrollPane1.setViewportView(output_view);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 306, 152));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stack2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stack2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        userValue = Integer.parseInt(inputValue.getText());
        arr.add(userValue);
        if ( i == 0 ){
        stack1.setText(Integer.toString(arr.get(i)));
        }
        if( i == 1) {
        stack2.setText(Integer.toString(arr.get(i)));
        }
        if( i == 2) {
        stack3.setText(Integer.toString(arr.get(i)));
        }
        if( i == 3) {
        stack4.setText(Integer.toString(arr.get(i)));
        }
        if( i == 4) {
         stack5.setText(Integer.toString(arr.get(i)));        
        }
         
        i++;
       
         if(i >= 5 ){
        JOptionPane.showMessageDialog(null,"Cannot input more!");
        }
        }catch(Exception e) {          
        JOptionPane.showMessageDialog(null,"Cannot input more!");
           
        }
        
        inputValue.setText("");
     
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        dispose(); 
        Main_Frame main = new Main_Frame(); 
        main.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        output_view.setText(arr.get(0).toString());
        output_view.setText(arr.get(1).toString());
        output_view.setText(arr.get(2).toString());
        output_view.setText(arr.get(3).toString());
        output_view.setText(arr.get(4).toString());
        
        String output = "";
        output += arr + " ";  
        output_view.setText(output);
        
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseClicked
      output_view.setText(arr.toString());
    }//GEN-LAST:event_btn_viewMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       
    }//GEN-LAST:event_jButton3MouseClicked
    int size = 4;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        arr.remove(size);
        String output = "";
        output += arr + " ";  
        output_view.setText(output);
        size--;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stack_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_view;
    private javax.swing.JButton home;
    private javax.swing.JTextField inputValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output_view;
    private javax.swing.JLabel pringle;
    private javax.swing.JTextField stack1;
    private javax.swing.JTextField stack2;
    private javax.swing.JTextField stack3;
    private javax.swing.JTextField stack4;
    private javax.swing.JTextField stack5;
    // End of variables declaration//GEN-END:variables
}
